modified shell script and Jenkinsfile

diff --git a/spring-boot-app/Jenkinsfile b/spring-boot-app/Jenkinsfile
--- a/spring-boot-app/Jenkinsfile
+++ b/spring-boot-app/Jenkinsfile
@@ -1,6 +1,8 @@
 pipeline {
     
-    agent any 
+    agent {
+        label 'unixAgent'
+    }
 
     tools {
         maven 'maven3'
@@ -13,13 +15,12 @@ pipeline {
         string(name: 'BUILD_ARTIFACT_DAYS_TO_KEEP', defaultValue: '2', description: 'Discard build artifacts older than specified days.')
         string(name: 'CONTAINER_PORT', defaultValue: '8084', description: 'Port to expose within the container.')
         choice(name: 'BRANCH_NAME', choices: ['main', 'dev', 'staging'], description: 'Git branch to build.')
-        choice(name: 'MAIL_TO', choices: ['samuelhaddison71@gmail.com', 'orionhouse83@gmail.com'], description: 'Email recipients')
+        choice(name: 'MAIL_TO', choices: ['samuelhaddison@gmail.com', 'orionhouse83@gmail.com'], description: 'Email recipients')
         choice(name: 'PROJECT_VERSION', choices: ['1.0', '1.1', '1.2'], description: 'Version of the project to build.')
-        choice(name: 'ENVIRONMENT', choices: ['dev', 'test', 'prod'], description: 'Environment to deploy to.')
-        choice(name: 'TRIVY_SEVERITY', choices: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'], description: 'Severity level for vulnerability scanning.')
+        choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Environment to deploy to.')
+        choice(name: 'TRIVY_SEVERITY', choices: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'], description: 'Severity level for vulnerability scan.')
         string(name: 'HOST_PORT', defaultValue: '8084', description: 'Host port for smoke testing.')
-        booleanParam(name: 'FAIL_ON_LEAKS', defaultValue: true, description: 'Fail the build if secrets are found in the source code.')  
-        booleanParam(name: 'FAIL_ON_ISSUES', defaultValue: true, description: 'Fail the build if Critical vulnerabilities are found in project dependencies.')    
+        booleanParam(name: 'FAIL_ON_LEAKS', defaultValue: true, description: 'Fail the build if secrets are found in the source code.') 
     }
 
     options {
@@ -34,27 +35,30 @@ pipeline {
     }
     
     environment {
+        // Define environment variables
+        // These variables are used throughout the pipeline for consistency and ease of maintenance
         GIT_URL = 'https://github.com/Orion83-h/java-app.git'
-        GIT_CREDS = 'gitAuth'
-        GHCR_USERNAME = 'Orion83-h'
         DOCKERFILE = 'spring-boot-app/Dockerfile.dev'
         DOCKER_NAMESPACE = 'colanta06'
         MAJOR_VERSION = "1"
         MINOR_VERSION = "0"
-        PATCH_VERSION = "${env.BUILD_NUMBER}" 
-        IMAGE_TAG = "v${MAJOR_VERSION}.${MINOR_VERSION}.${env.PATCH_VERSION}" 
+        PATCH_VERSION = "${env.BUILD_NUMBER}"
+        IMAGE_TAG = "v${MAJOR_VERSION}.${MINOR_VERSION}.${env.PATCH_VERSION}"
         IMAGE_NAME = "${DOCKER_NAMESPACE}/${env.JOB_NAME}:${env.IMAGE_TAG}"
         CONTAINER_NAME = "java-app-${params.ENVIRONMENT}"
         SONAR_ORG = 'hologram'
         SONAR_PROJECT_KEY = 'hologram_springapp'
-        TRIVY_CACHE_DIR = '/tmp/trivy' // default dir for trivy cache
+        TRIVY_CACHE_DIR = '/tmp/trivy'
         TRIVY_SCAN_STATUS = '0'
-        S3_BUCKET_NAME = "scanned-reports-pfljpz9wbk7drnk2"
+        S3_BUCKET_NAME = "scanned-reports-3wkxw7ls"
     }
 
     stages {
         stage('Pull Src Code') {
             steps {
+                // Pulls the source code from the specified Git repository
+                // The branch name is specified by the user as a parameter
+                // The depth of the Git clone is set to 1 to speed up the build proces (latest commit only) 
                 echo "====++++Pulling Source Code From Repo++++===="
                 checkout([$class: 'GitSCM',
                     branches: [[name: "*/${params.BRANCH_NAME}"]],
@@ -62,7 +66,7 @@ pipeline {
                     extensions: [
                         [$class: 'PruneStaleBranch'],
                         [$class: 'CleanBeforeCheckout'],
-                        [$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true]
+                        [$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true] // depth could be increased for larger repos
                     ],
                     userRemoteConfigs: [[credentialsId: env.GIT_CREDS, url: env.GIT_URL]]
                 ])
@@ -72,6 +76,10 @@ pipeline {
         stage('Secrets Scan (Gitleaks)') {
             steps {
                 script {
+                    // GitLeaks is a tool for detecting secrets leaked in source code repositories
+                    // It scans the source code for secrets and reports them
+                    // The scan is performed on the source code directory (spring-boot-app)
+                    // Report is generated in SARIF, XML, HTML, Junit or Text formats
                     echo "====++++Running Gitleaks for Secrets Scanning++++===="
                     sh """
                         mkdir -p gitleaks-reports
@@ -83,7 +91,8 @@ pipeline {
 
                     def result = sh(script: "gitleaks detect --source spring-boot-app --exit-code 1", returnStatus: true)
                     if (result != 0 && params.FAIL_ON_LEAKS) {
-                        error("Secrets detected by Gitleaks!")
+                        error("Secrets detected by Gitleaks!!")
+                        echo "Failing the build! Secrets detected in source code."
                     } else {
                         echo "No secrets detected by Gitleaks."
                     }
@@ -95,19 +104,25 @@ pipeline {
             steps {
                 echo "====++++Building Maven Project++++===="
                 dir('spring-boot-app') {
-                    sh 'mvn clean package -Dmaven.test.skip=true'
+                    sh 'mvn clean package -DskipTests'
                     sh 'ls -lrt target/'
                 }
             }
         }
 
         stage('Deploy To Nexus') {
+            // It could be any other artifact repository e.g. JFrog Artifactory*, AWS S3 etc.
+            // *JFrog Artifactory is a universal artifact repository manager
+            // It fully supports software packages created by any language or technology
+            // It is a Maven repository, npm registry, Ruby repository, etc.
+            // JFrog Xray is a security and compliance scanning tool that integrates with Artifactory
+            // It scans artifacts for vulnerabilities and compliance issues
             steps {
                 echo "====++++Deploying To Nexus++++===="
                 dir('spring-boot-app') {
                     withMaven(globalMavenSettingsConfig: 'settings', jdk: '', maven: 'maven3', mavenSettingsConfig: '', traceability: true) {
                         sh 'mvn deploy'
-                    }    
+                    }
                 }
             }
         }
@@ -136,34 +151,42 @@ pipeline {
 
         stage('Docker Operations') {
             failFast true
+            // The Docker operations are performed in parallel to speed up the build process 
+            // The Docker image is built with the latest dependencies and tagged with the version number 
+            // The version number is derived from the Jenkins build number which is incremented with each build (patch version)
             parallel {
                 stage('Check Dockerfile') {
+                    // Checks if a Dockerfile exists at the specified path
+                    // If the Dockerfile does not exist, the build will fail
+                    // The path to the Dockerfile is specified in the environment variables block
+                    // The Dockerfile in this case is located in the projects root directory
                     steps {
                         echo "====++++Checking Dockerfile++++===="
                         script {
-                            catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
-                                if (fileExists(env.DOCKERFILE)) {
-                                    echo "Dockerfile exists at path: ${env.DOCKERFILE}"
-                                } else {
-                                    error "Dockerfile does not exist at path: ${env.DOCKERFILE}"
-                                }
+                            if (!fileExists(env.DOCKERFILE)) {
+                                error "Dockerfile does not exist at path: ${env.DOCKERFILE}"
                             }
+                            echo "Dockerfile exists at path: ${env.DOCKERFILE}"
                         }
                     }
                 }
                 stage('Build Docker Image') {
+                    // Builds a Docker image using the Dockerfile
+                    // The image is tagged with the specified name and version\tag
+                    // The image is built with the `--no-cache` and `--pull` flags to ensure the latest dependencies are used
+                    when {
+                        expression { fileExists(env.DOCKERFILE) }
+                    }
                     steps {
                         echo "====++++Building Docker Image++++===="
                         script {
-                            catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
-                                sh """
-                                    docker build \
-                                    --no-cache \
-                                    --pull \
-                                    -t ${env.IMAGE_NAME} \
-                                    -f ${env.DOCKERFILE} .
-                                """
-                            }
+                            sh """
+                                docker build \
+                                --no-cache \
+                                --pull \
+                                -t ${env.IMAGE_NAME} \
+                                -f ${env.DOCKERFILE} . 
+                            """
                         }
                     }
                 }
@@ -208,8 +231,8 @@ pipeline {
                         // Authenticate and perform the scan
                         withCredentials([
                             usernamePassword(
-                                credentialsId: 'gitAuth', // Replace with your Jenkins credentials ID
-                                usernameVariable: 'GHCR_USERNAME',
+                                credentialsId: 'gitAuth', // Replace with your GitHub credentials ID as stored in Jenkins
+                                usernameVariable: 'GHCR_USERNAME', // Could use hashicorp vault or other secret management tools
                                 passwordVariable: 'GHCR_TOKEN'
                             )
                         ]) {
@@ -251,6 +274,8 @@ pipeline {
         }
 
         stage('Upload Trivy Report to S3') {
+            // Uploads the Trivy report to S3 bucket for further analysis
+            // The report is uploaded only if it exists and is not empty
             steps {
                 echo "====++++ Uploading Trivy Report to S3 ++++===="
                 script {
@@ -262,19 +287,19 @@ pipeline {
                     def reportSize = fileExists(reportPath) ? sh(script: "wc -c < ${reportPath}", returnStdout: true).trim().toInteger() : 0
 
                     if (reportSize > 0) {
-                        def uploadStatus = sh(script: "aws s3 cp ${reportPath} ${s3Url}", returnStatus: true)
-
-                        if (uploadStatus != 0) {
-                            error("Failed to upload Trivy report to S3: ${s3Url}")
+                        try {
+                            sh "aws s3 cp ${reportPath} ${s3Url}"
+                            echo "Trivy report uploaded successfully to S3: ${s3Url}"
+                        } catch (Exception e) {
+                            error("Failed to upload Trivy report to S3: ${s3Url}. Error: ${e.getMessage()}")
                         }
-                        echo "Trivy report uploaded successfully to S3: ${s3Url}"
                     } else {
                         echo "Trivy report not found or empty; skipping upload."
                     }
                 }
             }
         }
-        // Docker image push is triggered based on the result from the prior stage (Trivy scan)
+        
         stage('Push Docker Image') {
             when {
                 expression { 
@@ -282,9 +307,10 @@ pipeline {
                 }  
             }
             steps {
+                // Docker image push is triggered based on the result from the (Trivy scan)
                 echo "====++++Pushing Docker Image to Registry++++===="
                 script {
-                    def dockerRegistryUrl = 'https://index.docker.io/v1/' // Here we're using Docker Hub as Image Registry
+                    def dockerRegistryUrl = 'https://registry-1.docker.io/' // Here we're using Docker Hub as Image Registry
                     withDockerRegistry([credentialsId: 'dockerId', url: dockerRegistryUrl]) {
                         retry(3) {
                             sh "docker push ${env.IMAGE_NAME}"
@@ -295,35 +321,46 @@ pipeline {
         }
 
         stage('Smoke Test') {
+            // It is recommended to have a smoke test to verify the application is running as expected
+            // Here we are running a simple shell script to check the application status. The script is located in the project root 
+            // It could be a simple curl command or a more complex test suite
             steps {
                 echo "====++++Executing Smoke Test++++===="
                 script {
                     def hostPort = params.HOST_PORT.toInteger()
-                    sh """
-                        docker run --name ${env.CONTAINER_NAME} \
-                            -d \
-                            -p ${hostPort}:${params.CONTAINER_PORT} \
-                            ${env.IMAGE_NAME}
-                    """
-                    sh "chmod +x ${WORKSPACE}/spring-boot-app/check.sh"
-                    sh """
-                        sleep 30
-                        APP_PORT=${hostPort} ${WORKSPACE}/spring-boot-app/check.sh
-                    """
+                    try {
+                        sh """
+                            docker run --name ${env.CONTAINER_NAME} \
+                                -d \
+                                -p ${hostPort}:${params.CONTAINER_PORT} \
+                                ${env.IMAGE_NAME}
+                        """
+                        sh "chmod +x ${WORKSPACE}/spring-boot-app/check.sh"
+                        sh """
+                            sleep 30
+                            APP_PORT=${hostPort} ${WORKSPACE}/spring-boot-app/check.sh
+                        """
+                    } catch (Exception e) {
+                        error("Smoke test failed: ${e.getMessage()}")
+                    }
                 }
             }
-        }
+        }}
 
         stage('Cleanup') {
             steps {
+                // The Docker container and image are stopped and removed after the build is complete 
+                // This is to ensure that the environment is clean and ready for the next build
                 echo "====++++Cleaning up++++===="
                 script {
-                    sh """
-                    docker stop ${env.CONTAINER_NAME} || true
-                    docker rm -f ${env.CONTAINER_NAME} || true
-                    docker rmi -f ${env.IMAGE_NAME} || true
-                    docker ps -a
-                """
+                    try {
+                        sh "docker stop ${env.CONTAINER_NAME} 2>&1 > /dev/null || echo 'Container ${env.CONTAINER_NAME} not found.'"
+                        sh "docker rm -f ${env.CONTAINER_NAME} 2>&1 > /dev/null || echo 'Container ${env.CONTAINER_NAME} not found.'"
+                        sh "docker rmi -f ${env.IMAGE_NAME} 2>&1 > /dev/null || echo 'Image ${env.IMAGE_NAME} not found.'"
+                        sh "docker ps -a"
+                    } catch (Exception e) {
+                        echo "Cleanup failed: ${e.getMessage()}"
+                    }
                 }
             }
         }
@@ -336,6 +373,8 @@ pipeline {
                 def depCheckReportUrl = "${env.BUILD_URL}artifact/dependency-check-reports/dependency-check-report.html"
 
                 // Trigger downstream Helm Chart update job
+                // This job updates the Helm chart with the new image tag
+                // The Helm chart is then deployed to the Kubernetes cluster using ArgoCD or Helm CLI
                 build job: 'helm-chart-update', 
                     parameters: [
                         string(name: 'IMAGE_NAME', value: "${env.IMAGE_NAME}"),
@@ -343,6 +382,8 @@ pipeline {
                         string(name: 'ENVIRONMENT', value: "${params.ENVIRONMENT}")
                     ]
                 // Email notification
+                // Sends an email notification with the build status and relevant information
+                // The email contains links to the build details, Trivy scan report, and other relevant information
                 emailext (
                     to: "${params.MAIL_TO}",
                     subject: "SUCCESS: ${env.JOB_NAME} - Build ${env.BUILD_NUMBER}",
@@ -394,3 +435,4 @@ pipeline {
         }
     }
 }
+
